from app import schema, types as _types


class _TypesProxy:
    Move = schema.Move
    MoveEffect = schema.MoveEffect
    VibemonTypeT = _types.VibemonTypeT
    MoveCategoryT = _types.MoveCategoryT
    StatusConditionT = _types.StatusConditionT


types = _TypesProxy()


MOVES = [
    # ── Ice (freezing temps, snow, ice in condition text) ───────────────────────────
    types.Move(
        name="Black Ice Shard",
        flavor_text="Hidden glaze on the road made solid—sharp, sudden, and mean.",
        type=types.VibemonTypeT.ICE,
        category=types.MoveCategoryT.PHYSICAL,
        power=55,
        accuracy=0.95,
    ),
    types.Move(
        name="Rime Needle",
        flavor_text="Needles of frost stitch the air where breath used to be.",
        type=types.VibemonTypeT.ICE,
        category=types.MoveCategoryT.SPECIAL,
        power=45,
        accuracy=1.0,
    ),
    types.Move(
        name="Polar Vortex Clamp",
        flavor_text="A spinning pocket of arctic air settles and will not let go.",
        type=types.VibemonTypeT.ICE,
        category=types.MoveCategoryT.SPECIAL,
        power=90,
        accuracy=0.85,
    ),
    types.Move(
        name="Hail Core Pelting",
        flavor_text="The radar blob deepens; ice pellets drum the field like static.",
        type=types.VibemonTypeT.ICE,
        category=types.MoveCategoryT.PHYSICAL,
        power=70,
        accuracy=0.9,
    ),
    types.Move(
        name="Flash Freeze",
        flavor_text="The mercury nose-dives; still water becomes threat in one frame.",
        type=types.VibemonTypeT.ICE,
        category=types.MoveCategoryT.STATUS,
        power=None,
        accuracy=0.8,
        effect=types.MoveEffect(status_inflict=types.StatusConditionT.FREEZE, chance=0.35),
    ),
    # ── Fire (heat wave, 32 °C+ on the dial) ─────────────────────────────────────────
    types.Move(
        name="Heat Index Surge",
        flavor_text="Humid air and scorching mercury gang up until shade lies.",
        type=types.VibemonTypeT.FIRE,
        category=types.MoveCategoryT.SPECIAL,
        power=95,
        accuracy=0.9,
    ),
    types.Move(
        name="Scorching High",
        flavor_text="The afternoon high printed bold on the forecast—no asterisk.",
        type=types.VibemonTypeT.FIRE,
        category=types.MoveCategoryT.SPECIAL,
        power=85,
        accuracy=0.95,
    ),
    types.Move(
        name="Sunstroke Beam",
        flavor_text="Sky-clear and merciless; the kind of day that browns the lawn.",
        type=types.VibemonTypeT.FIRE,
        category=types.MoveCategoryT.SPECIAL,
        power=110,
        accuracy=0.8,
    ),
    types.Move(
        name="Thermal Shimmer Lash",
        flavor_text="Heat haze bends the horizon, then snaps forward like a mirage whip.",
        type=types.VibemonTypeT.FIRE,
        category=types.MoveCategoryT.SPECIAL,
        power=50,
        accuracy=0.85,
    ),
    types.Move(
        name="UV Microflare",
        flavor_text="Thin ozone, high noon—an invisible brand on anything exposed.",
        type=types.VibemonTypeT.FIRE,
        category=types.MoveCategoryT.PHYSICAL,
        power=60,
        accuracy=1.0,
        effect=types.MoveEffect(status_inflict=types.StatusConditionT.BURN, chance=0.2),
    ),
    # ── Water (rain, drizzle, precip) ───────────────────────────────────────────────
    types.Move(
        name="Sheet Rain",
        flavor_text="The radar greens; water falls in one continuous curtain.",
        type=types.VibemonTypeT.WATER,
        category=types.MoveCategoryT.SPECIAL,
        power=55,
        accuracy=1.0,
    ),
    types.Move(
        name="Downpour Driver",
        flavor_text="Street rivers rise; drains choke—this is the red cell on the map.",
        type=types.VibemonTypeT.WATER,
        category=types.MoveCategoryT.SPECIAL,
        power=100,
        accuracy=0.8,
    ),
    types.Move(
        name="Virga Lash",
        flavor_text="Rain that never lands—evaporates—yet leaves a soaking sting.",
        type=types.VibemonTypeT.WATER,
        category=types.MoveCategoryT.SPECIAL,
        power=40,
        accuracy=0.95,
    ),
    types.Move(
        name="Monsoon Spiral",
        flavor_text="Bands of moisture wheel inward like a satellite loop come alive.",
        type=types.VibemonTypeT.WATER,
        category=types.MoveCategoryT.SPECIAL,
        power=75,
        accuracy=0.9,
    ),
    types.Move(
        name="Drizzle Needle",
        flavor_text="Light precip—almost polite—until a million tiny points add up.",
        type=types.VibemonTypeT.WATER,
        category=types.MoveCategoryT.PHYSICAL,
        power=35,
        accuracy=1.0,
    ),
    # ── Grass (humid air, growth, canopy) ───────────────────────────────────────────
    types.Move(
        name="Dew Point Bloom",
        flavor_text="Air heavy enough to drink; every leaf swells overnight.",
        type=types.VibemonTypeT.GRASS,
        category=types.MoveCategoryT.SPECIAL,
        power=45,
        accuracy=1.0,
    ),
    types.Move(
        name="Muggy Spore Drift",
        flavor_text="Spores ride invisible rivers of humidity straight to the lungs.",
        type=types.VibemonTypeT.GRASS,
        category=types.MoveCategoryT.STATUS,
        power=None,
        accuracy=0.75,
        effect=types.MoveEffect(status_inflict=types.StatusConditionT.SLEEP, chance=0.4),
    ),
    types.Move(
        name="Canopy Whip",
        flavor_text="Wind meets wet leaves; the forest answers with a slap.",
        type=types.VibemonTypeT.GRASS,
        category=types.MoveCategoryT.PHYSICAL,
        power=65,
        accuracy=0.95,
    ),
    types.Move(
        name="Chlorophyll Rush",
        flavor_text="Storms fed the soil; growth does not ask permission.",
        type=types.VibemonTypeT.GRASS,
        category=types.MoveCategoryT.PHYSICAL,
        power=55,
        accuracy=1.0,
        priority=1,
    ),
    types.Move(
        name="Humid Root Grasp",
        flavor_text="Roots probe softer earth where water tables rose after the rain.",
        type=types.VibemonTypeT.GRASS,
        category=types.MoveCategoryT.PHYSICAL,
        power=50,
        accuracy=1.0,
        effect=types.MoveEffect(stat_changes={"speed": -1}, chance=0.3),
    ),
    # ── Flying (wind, jet stream, gusts) ──────────────────────────────────────────────
    types.Move(
        name="Gust Front",
        flavor_text="The leading edge of a storm cell announces itself with a shove.",
        type=types.VibemonTypeT.FLYING,
        category=types.MoveCategoryT.SPECIAL,
        power=60,
        accuracy=0.95,
    ),
    types.Move(
        name="Jet Stream Shear",
        flavor_text="Upper-level winds do not care what is tethered below.",
        type=types.VibemonTypeT.FLYING,
        category=types.MoveCategoryT.SPECIAL,
        power=85,
        accuracy=0.85,
    ),
    types.Move(
        name="Crosswind Cut",
        flavor_text="Landing cancelled; sideways air scrapes like a blade.",
        type=types.VibemonTypeT.FLYING,
        category=types.MoveCategoryT.PHYSICAL,
        power=70,
        accuracy=0.9,
    ),
    types.Move(
        name="Anemometer Spin",
        flavor_text="Cups blur on the mast—numbers climb faster than sense.",
        type=types.VibemonTypeT.FLYING,
        category=types.MoveCategoryT.PHYSICAL,
        power=45,
        accuracy=1.0,
    ),
    types.Move(
        name="Downdraft Slam",
        flavor_text="A column of sinking air pins everything that thought it could fly.",
        type=types.VibemonTypeT.FLYING,
        category=types.MoveCategoryT.PHYSICAL,
        power=95,
        accuracy=0.8,
    ),
    # ── Rock (low visibility, mountains in the murk) ──────────────────────────────────
    types.Move(
        name="Crag Silhouette",
        flavor_text="Through fog, stone only shows when it is already too close.",
        type=types.VibemonTypeT.ROCK,
        category=types.MoveCategoryT.PHYSICAL,
        power=60,
        accuracy=0.9,
    ),
    types.Move(
        name="Boulder Outcrop",
        flavor_text="Bedrock shrugged free by freeze-thaw—gravity does the rest.",
        type=types.VibemonTypeT.ROCK,
        category=types.MoveCategoryT.PHYSICAL,
        power=80,
        accuracy=0.85,
    ),
    types.Move(
        name="Scree Slide",
        flavor_text="Loose stone chatters downslope like applause with teeth.",
        type=types.VibemonTypeT.ROCK,
        category=types.MoveCategoryT.PHYSICAL,
        power=55,
        accuracy=0.95,
    ),
    types.Move(
        name="Foghorn Resonance",
        flavor_text="Sound carries weird in the murk—stone channels it into a blow.",
        type=types.VibemonTypeT.ROCK,
        category=types.MoveCategoryT.SPECIAL,
        power=50,
        accuracy=1.0,
    ),
    types.Move(
        name="Landslip Hammer",
        flavor_text="Saturation plus slope; the hillside votes to relocate.",
        type=types.VibemonTypeT.ROCK,
        category=types.MoveCategoryT.PHYSICAL,
        power=100,
        accuracy=0.75,
    ),
    # ── Ground (fog hugging the deck, low vis) ───────────────────────────────────────
    types.Move(
        name="Deck Fog Roll",
        flavor_text="Moisture pools along the surface until the world has no ankles.",
        type=types.VibemonTypeT.GROUND,
        category=types.MoveCategoryT.SPECIAL,
        power=45,
        accuracy=1.0,
    ),
    types.Move(
        name="Visibility Zero Trench",
        flavor_text="Less than a kilometer on the report—distance becomes theory.",
        type=types.VibemonTypeT.GROUND,
        category=types.MoveCategoryT.PHYSICAL,
        power=70,
        accuracy=0.85,
    ),
    types.Move(
        name="Saturated Soil Hook",
        flavor_text="Footing betrays; the earth remembers every drop that fell.",
        type=types.VibemonTypeT.GROUND,
        category=types.MoveCategoryT.PHYSICAL,
        power=65,
        accuracy=0.9,
        effect=types.MoveEffect(stat_changes={"speed": -1}, chance=0.25),
    ),
    types.Move(
        name="Contour Line Burrow",
        flavor_text="Following elevation like a secret—the slow line always wins.",
        type=types.VibemonTypeT.GROUND,
        category=types.MoveCategoryT.PHYSICAL,
        power=55,
        accuracy=0.95,
    ),
    types.Move(
        name="Isobar Stamp",
        flavor_text="Pressure printed on the map becomes weight you can feel.",
        type=types.VibemonTypeT.GROUND,
        category=types.MoveCategoryT.PHYSICAL,
        power=85,
        accuracy=0.8,
    ),
    # ── Electric (thunder in condition text) ─────────────────────────────────────────
    types.Move(
        name="Cloud-to-Ground Bolt",
        flavor_text="The strike the warning triangle was invented for.",
        type=types.VibemonTypeT.ELECTRIC,
        category=types.MoveCategoryT.SPECIAL,
        power=95,
        accuracy=0.75,
        effect=types.MoveEffect(status_inflict=types.StatusConditionT.PARALYSIS, chance=0.3),
    ),
    types.Move(
        name="Sheet Lightning Glow",
        flavor_text="The whole sky flickers—charge without a single clean address.",
        type=types.VibemonTypeT.ELECTRIC,
        category=types.MoveCategoryT.SPECIAL,
        power=65,
        accuracy=0.95,
    ),
    types.Move(
        name="Ionized Gust",
        flavor_text="Wind rubs droplets until the air itself tastes metallic.",
        type=types.VibemonTypeT.ELECTRIC,
        category=types.MoveCategoryT.SPECIAL,
        power=55,
        accuracy=0.9,
    ),
    types.Move(
        name="Thunderhead Core",
        flavor_text="The anvil’s heart—where the forecast writes ‘severe’ in caps.",
        type=types.VibemonTypeT.ELECTRIC,
        category=types.MoveCategoryT.SPECIAL,
        power=110,
        accuracy=0.7,
    ),
    types.Move(
        name="Static Hair Snap",
        flavor_text="Dry air after the cell passes—small sparks, big attitude.",
        type=types.VibemonTypeT.ELECTRIC,
        category=types.MoveCategoryT.PHYSICAL,
        power=40,
        accuracy=1.0,
        effect=types.MoveEffect(status_inflict=types.StatusConditionT.PARALYSIS, chance=0.15),
    ),
    # ── Dark (night, is_day == 0) ───────────────────────────────────────────────────
    types.Move(
        name="Astronomical Twilight",
        flavor_text="The sun is gone but law lingers—shadows keep their contracts.",
        type=types.VibemonTypeT.DARK,
        category=types.MoveCategoryT.SPECIAL,
        power=55,
        accuracy=0.95,
    ),
    types.Move(
        name="Curfew Veil",
        flavor_text="Streetlights click on; what moves between pools is not yours.",
        type=types.VibemonTypeT.DARK,
        category=types.MoveCategoryT.PHYSICAL,
        power=70,
        accuracy=0.9,
    ),
    types.Move(
        name="New Moon Clause",
        flavor_text="No borrowed light—only terms written in absence.",
        type=types.VibemonTypeT.DARK,
        category=types.MoveCategoryT.SPECIAL,
        power=80,
        accuracy=0.85,
    ),
    types.Move(
        name="Umbra Pinch",
        flavor_text="The cool side of the planet leans in until color drains.",
        type=types.VibemonTypeT.DARK,
        category=types.MoveCategoryT.PHYSICAL,
        power=60,
        accuracy=1.0,
        effect=types.MoveEffect(stat_changes={"sp_defense": -1}, chance=0.25),
    ),
    types.Move(
        name="Light Pollution Snuff",
        flavor_text="Even false stars get filed away—dark wins on points.",
        type=types.VibemonTypeT.DARK,
        category=types.MoveCategoryT.STATUS,
        power=None,
        accuracy=0.85,
        effect=types.MoveEffect(stat_changes={"accuracy": -1}, chance=0.5),
    ),
    # ── Ghost (night + fog spirits) ─────────────────────────────────────────────────
    types.Move(
        name="Vapor Wisp",
        flavor_text="Condensation holds a face for half a breath, then denies it.",
        type=types.VibemonTypeT.GHOST,
        category=types.MoveCategoryT.SPECIAL,
        power=45,
        accuracy=1.0,
    ),
    types.Move(
        name="Fog Echo",
        flavor_text="Footsteps return from the wrong direction—no body attached.",
        type=types.VibemonTypeT.GHOST,
        category=types.MoveCategoryT.SPECIAL,
        power=60,
        accuracy=0.95,
    ),
    types.Move(
        name="Haar Drift",
        flavor_text="Sea fog rolls inland—salt, chill, and old stories in one bank.",
        type=types.VibemonTypeT.GHOST,
        category=types.MoveCategoryT.SPECIAL,
        power=70,
        accuracy=0.9,
    ),
    types.Move(
        name="Spectral Barometer",
        flavor_text="Pressure drops; something inventories the room you thought was empty.",
        type=types.VibemonTypeT.GHOST,
        category=types.MoveCategoryT.SPECIAL,
        power=55,
        accuracy=0.95,
        effect=types.MoveEffect(stat_changes={"sp_attack": -1}, chance=0.2),
    ),
    types.Move(
        name="Midnight Apparition",
        flavor_text="The forecast said clear; the window said otherwise.",
        type=types.VibemonTypeT.GHOST,
        category=types.MoveCategoryT.PHYSICAL,
        power=85,
        accuracy=0.85,
    ),
    # ── Normal (clear, calm daytime default) ────────────────────────────────────────
    types.Move(
        name="Fair Skies Nod",
        flavor_text="High pressure, polite breeze—the boring icon everyone wants.",
        type=types.VibemonTypeT.NORMAL,
        category=types.MoveCategoryT.PHYSICAL,
        power=40,
        accuracy=1.0,
    ),
    types.Move(
        name="Isobaric Calm",
        flavor_text="Lines wide on the chart; nothing argues, nothing hurries.",
        type=types.VibemonTypeT.NORMAL,
        category=types.MoveCategoryT.SPECIAL,
        power=50,
        accuracy=1.0,
    ),
    types.Move(
        name="Partly Cloudy Glance",
        flavor_text="Sun and shade trade turns—predictable, comfortable, smug.",
        type=types.VibemonTypeT.NORMAL,
        category=types.MoveCategoryT.SPECIAL,
        power=55,
        accuracy=0.95,
    ),
    types.Move(
        name="Comfort Index Tap",
        flavor_text="Not too hot, not too wet—statistics pretending to be kindness.",
        type=types.VibemonTypeT.NORMAL,
        category=types.MoveCategoryT.PHYSICAL,
        power=45,
        accuracy=1.0,
    ),
    types.Move(
        name="Station Model Shrug",
        flavor_text="All sensors green; the day refuses drama—and lulls the guard.",
        type=types.VibemonTypeT.NORMAL,
        category=types.MoveCategoryT.STATUS,
        power=None,
        accuracy=1.0,
        effect=types.MoveEffect(stat_changes={"accuracy": -1}, chance=0.45),
    ),
]
