from app import types

TYPE_CHART: dict[tuple[types.VibemonT, types.VibemonT], float] = {
    (types.VibemonT.NORMAL, types.VibemonT.ROCK): 0.5,
    (types.VibemonT.NORMAL, types.VibemonT.GHOST): 0.0,
    (types.VibemonT.NORMAL, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.FIRE, types.VibemonT.FIRE): 0.5,
    (types.VibemonT.FIRE, types.VibemonT.WATER): 0.5,
    (types.VibemonT.FIRE, types.VibemonT.GRASS): 2.0,
    (types.VibemonT.FIRE, types.VibemonT.ICE): 2.0,
    (types.VibemonT.FIRE, types.VibemonT.BUG): 2.0,
    (types.VibemonT.FIRE, types.VibemonT.ROCK): 0.5,
    (types.VibemonT.FIRE, types.VibemonT.DRAGON): 0.5,
    (types.VibemonT.WATER, types.VibemonT.FIRE): 2.0,
    (types.VibemonT.WATER, types.VibemonT.WATER): 0.5,
    (types.VibemonT.WATER, types.VibemonT.GRASS): 0.5,
    (types.VibemonT.WATER, types.VibemonT.GROUND): 2.0,
    (types.VibemonT.WATER, types.VibemonT.ROCK): 2.0,
    (types.VibemonT.WATER, types.VibemonT.DRAGON): 0.5,
    (types.VibemonT.ELECTRIC, types.VibemonT.WATER): 2.0,
    (types.VibemonT.ELECTRIC, types.VibemonT.ELECTRIC): 0.5,
    (types.VibemonT.ELECTRIC, types.VibemonT.GRASS): 0.5,
    (types.VibemonT.ELECTRIC, types.VibemonT.GROUND): 0.0,
    (types.VibemonT.ELECTRIC, types.VibemonT.FLYING): 2.0,
    (types.VibemonT.ELECTRIC, types.VibemonT.DRAGON): 0.5,
    (types.VibemonT.GRASS, types.VibemonT.FIRE): 0.5,
    (types.VibemonT.GRASS, types.VibemonT.WATER): 2.0,
    (types.VibemonT.GRASS, types.VibemonT.GRASS): 0.5,
    (types.VibemonT.GRASS, types.VibemonT.POISON): 0.5,
    (types.VibemonT.GRASS, types.VibemonT.GROUND): 2.0,
    (types.VibemonT.GRASS, types.VibemonT.FLYING): 0.5,
    (types.VibemonT.GRASS, types.VibemonT.BUG): 0.5,
    (types.VibemonT.GRASS, types.VibemonT.ROCK): 2.0,
    (types.VibemonT.GRASS, types.VibemonT.DRAGON): 0.5,
    (types.VibemonT.GRASS, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.ICE, types.VibemonT.FIRE): 0.5,
    (types.VibemonT.ICE, types.VibemonT.WATER): 0.5,
    (types.VibemonT.ICE, types.VibemonT.GRASS): 2.0,
    (types.VibemonT.ICE, types.VibemonT.ICE): 0.5,
    (types.VibemonT.ICE, types.VibemonT.GROUND): 2.0,
    (types.VibemonT.ICE, types.VibemonT.FLYING): 2.0,
    (types.VibemonT.ICE, types.VibemonT.DRAGON): 2.0,
    (types.VibemonT.ICE, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.FIGHTING, types.VibemonT.NORMAL): 2.0,
    (types.VibemonT.FIGHTING, types.VibemonT.ICE): 2.0,
    (types.VibemonT.FIGHTING, types.VibemonT.POISON): 0.5,
    (types.VibemonT.FIGHTING, types.VibemonT.FLYING): 0.5,
    (types.VibemonT.FIGHTING, types.VibemonT.PSYCHIC): 0.5,
    (types.VibemonT.FIGHTING, types.VibemonT.BUG): 0.5,
    (types.VibemonT.FIGHTING, types.VibemonT.ROCK): 2.0,
    (types.VibemonT.FIGHTING, types.VibemonT.GHOST): 0.0,
    (types.VibemonT.FIGHTING, types.VibemonT.DARK): 2.0,
    (types.VibemonT.FIGHTING, types.VibemonT.STEEL): 2.0,
    (types.VibemonT.FIGHTING, types.VibemonT.FAIRY): 0.5,
    (types.VibemonT.POISON, types.VibemonT.GRASS): 2.0,
    (types.VibemonT.POISON, types.VibemonT.POISON): 0.5,
    (types.VibemonT.POISON, types.VibemonT.GROUND): 0.5,
    (types.VibemonT.POISON, types.VibemonT.ROCK): 0.5,
    (types.VibemonT.POISON, types.VibemonT.GHOST): 0.5,
    (types.VibemonT.POISON, types.VibemonT.STEEL): 0.0,
    (types.VibemonT.POISON, types.VibemonT.FAIRY): 2.0,
    (types.VibemonT.GROUND, types.VibemonT.FIRE): 2.0,
    (types.VibemonT.GROUND, types.VibemonT.ELECTRIC): 2.0,
    (types.VibemonT.GROUND, types.VibemonT.GRASS): 0.5,
    (types.VibemonT.GROUND, types.VibemonT.POISON): 2.0,
    (types.VibemonT.GROUND, types.VibemonT.FLYING): 0.0,
    (types.VibemonT.GROUND, types.VibemonT.BUG): 0.5,
    (types.VibemonT.GROUND, types.VibemonT.ROCK): 2.0,
    (types.VibemonT.GROUND, types.VibemonT.STEEL): 2.0,
    (types.VibemonT.FLYING, types.VibemonT.ELECTRIC): 0.5,
    (types.VibemonT.FLYING, types.VibemonT.GRASS): 2.0,
    (types.VibemonT.FLYING, types.VibemonT.FIGHTING): 2.0,
    (types.VibemonT.FLYING, types.VibemonT.BUG): 2.0,
    (types.VibemonT.FLYING, types.VibemonT.ROCK): 0.5,
    (types.VibemonT.FLYING, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.PSYCHIC, types.VibemonT.FIGHTING): 2.0,
    (types.VibemonT.PSYCHIC, types.VibemonT.POISON): 2.0,
    (types.VibemonT.PSYCHIC, types.VibemonT.PSYCHIC): 0.5,
    (types.VibemonT.PSYCHIC, types.VibemonT.DARK): 0.0,
    (types.VibemonT.PSYCHIC, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.BUG, types.VibemonT.FIRE): 0.5,
    (types.VibemonT.BUG, types.VibemonT.GRASS): 2.0,
    (types.VibemonT.BUG, types.VibemonT.FIGHTING): 0.5,
    (types.VibemonT.BUG, types.VibemonT.POISON): 0.5,
    (types.VibemonT.BUG, types.VibemonT.FLYING): 0.5,
    (types.VibemonT.BUG, types.VibemonT.PSYCHIC): 2.0,
    (types.VibemonT.BUG, types.VibemonT.GHOST): 0.5,
    (types.VibemonT.BUG, types.VibemonT.DARK): 2.0,
    (types.VibemonT.BUG, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.BUG, types.VibemonT.FAIRY): 0.5,
    (types.VibemonT.ROCK, types.VibemonT.FIRE): 2.0,
    (types.VibemonT.ROCK, types.VibemonT.ICE): 2.0,
    (types.VibemonT.ROCK, types.VibemonT.FIGHTING): 0.5,
    (types.VibemonT.ROCK, types.VibemonT.GROUND): 0.5,
    (types.VibemonT.ROCK, types.VibemonT.FLYING): 2.0,
    (types.VibemonT.ROCK, types.VibemonT.BUG): 2.0,
    (types.VibemonT.ROCK, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.GHOST, types.VibemonT.NORMAL): 0.0,
    (types.VibemonT.GHOST, types.VibemonT.PSYCHIC): 2.0,
    (types.VibemonT.GHOST, types.VibemonT.GHOST): 2.0,
    (types.VibemonT.GHOST, types.VibemonT.DARK): 0.5,
    (types.VibemonT.DRAGON, types.VibemonT.DRAGON): 2.0,
    (types.VibemonT.DRAGON, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.DRAGON, types.VibemonT.FAIRY): 0.0,
    (types.VibemonT.DARK, types.VibemonT.PSYCHIC): 2.0,
    (types.VibemonT.DARK, types.VibemonT.GHOST): 2.0,
    (types.VibemonT.DARK, types.VibemonT.DARK): 0.5,
    (types.VibemonT.DARK, types.VibemonT.FAIRY): 0.5,
    (types.VibemonT.STEEL, types.VibemonT.FIRE): 0.5,
    (types.VibemonT.STEEL, types.VibemonT.WATER): 0.5,
    (types.VibemonT.STEEL, types.VibemonT.ELECTRIC): 0.5,
    (types.VibemonT.STEEL, types.VibemonT.ICE): 2.0,
    (types.VibemonT.STEEL, types.VibemonT.ROCK): 2.0,
    (types.VibemonT.STEEL, types.VibemonT.STEEL): 0.5,
    (types.VibemonT.STEEL, types.VibemonT.FAIRY): 2.0,
    (types.VibemonT.FAIRY, types.VibemonT.FIRE): 0.5,
    (types.VibemonT.FAIRY, types.VibemonT.FIGHTING): 2.0,
    (types.VibemonT.FAIRY, types.VibemonT.POISON): 0.5,
    (types.VibemonT.FAIRY, types.VibemonT.DRAGON): 2.0,
    (types.VibemonT.FAIRY, types.VibemonT.DARK): 2.0,
    (types.VibemonT.FAIRY, types.VibemonT.STEEL): 0.5,
}


def get_type_effectiveness(attack_type: types.VibemonT, defender_types: list[types.VibemonT]) -> float:
    """
    Multiply the attacker's type modifier against each of the defender's types.

    Dual Type defenders produce combined multipliers
      4.00x = double weakness
      0.25x = double resistance
      1.00x = neutralization, when one type is weak and the other resists
      0.00x = absolute immunity, immunity on either type trumps any weakness on the other
    """
    modifier = 1.0

    for defender_type in defender_types:
        modifier *= TYPE_CHART.get((attack_type, defender_type), 1.0)

    return modifier
