from app import types

TYPE_CHART: dict[tuple[types.VibemonTypeT, types.VibemonTypeT], float] = {
    (types.VibemonTypeT.NORMAL, types.VibemonTypeT.ROCK): 0.5,
    (types.VibemonTypeT.NORMAL, types.VibemonTypeT.GHOST): 0.0,
    (types.VibemonTypeT.NORMAL, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.FIRE, types.VibemonTypeT.FIRE): 0.5,
    (types.VibemonTypeT.FIRE, types.VibemonTypeT.WATER): 0.5,
    (types.VibemonTypeT.FIRE, types.VibemonTypeT.GRASS): 2.0,
    (types.VibemonTypeT.FIRE, types.VibemonTypeT.ICE): 2.0,
    (types.VibemonTypeT.FIRE, types.VibemonTypeT.BUG): 2.0,
    (types.VibemonTypeT.FIRE, types.VibemonTypeT.ROCK): 0.5,
    (types.VibemonTypeT.FIRE, types.VibemonTypeT.DRAGON): 0.5,
    (types.VibemonTypeT.WATER, types.VibemonTypeT.FIRE): 2.0,
    (types.VibemonTypeT.WATER, types.VibemonTypeT.WATER): 0.5,
    (types.VibemonTypeT.WATER, types.VibemonTypeT.GRASS): 0.5,
    (types.VibemonTypeT.WATER, types.VibemonTypeT.GROUND): 2.0,
    (types.VibemonTypeT.WATER, types.VibemonTypeT.ROCK): 2.0,
    (types.VibemonTypeT.WATER, types.VibemonTypeT.DRAGON): 0.5,
    (types.VibemonTypeT.ELECTRIC, types.VibemonTypeT.WATER): 2.0,
    (types.VibemonTypeT.ELECTRIC, types.VibemonTypeT.ELECTRIC): 0.5,
    (types.VibemonTypeT.ELECTRIC, types.VibemonTypeT.GRASS): 0.5,
    (types.VibemonTypeT.ELECTRIC, types.VibemonTypeT.GROUND): 0.0,
    (types.VibemonTypeT.ELECTRIC, types.VibemonTypeT.FLYING): 2.0,
    (types.VibemonTypeT.ELECTRIC, types.VibemonTypeT.DRAGON): 0.5,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.FIRE): 0.5,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.WATER): 2.0,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.GRASS): 0.5,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.POISON): 0.5,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.GROUND): 2.0,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.FLYING): 0.5,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.BUG): 0.5,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.ROCK): 2.0,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.DRAGON): 0.5,
    (types.VibemonTypeT.GRASS, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.FIRE): 0.5,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.WATER): 0.5,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.GRASS): 2.0,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.ICE): 0.5,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.GROUND): 2.0,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.FLYING): 2.0,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.DRAGON): 2.0,
    (types.VibemonTypeT.ICE, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.NORMAL): 2.0,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.ICE): 2.0,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.POISON): 0.5,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.FLYING): 0.5,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.PSYCHIC): 0.5,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.BUG): 0.5,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.ROCK): 2.0,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.GHOST): 0.0,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.DARK): 2.0,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.STEEL): 2.0,
    (types.VibemonTypeT.FIGHTING, types.VibemonTypeT.FAIRY): 0.5,
    (types.VibemonTypeT.POISON, types.VibemonTypeT.GRASS): 2.0,
    (types.VibemonTypeT.POISON, types.VibemonTypeT.POISON): 0.5,
    (types.VibemonTypeT.POISON, types.VibemonTypeT.GROUND): 0.5,
    (types.VibemonTypeT.POISON, types.VibemonTypeT.ROCK): 0.5,
    (types.VibemonTypeT.POISON, types.VibemonTypeT.GHOST): 0.5,
    (types.VibemonTypeT.POISON, types.VibemonTypeT.STEEL): 0.0,
    (types.VibemonTypeT.POISON, types.VibemonTypeT.FAIRY): 2.0,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.FIRE): 2.0,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.ELECTRIC): 2.0,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.GRASS): 0.5,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.POISON): 2.0,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.FLYING): 0.0,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.BUG): 0.5,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.ROCK): 2.0,
    (types.VibemonTypeT.GROUND, types.VibemonTypeT.STEEL): 2.0,
    (types.VibemonTypeT.FLYING, types.VibemonTypeT.ELECTRIC): 0.5,
    (types.VibemonTypeT.FLYING, types.VibemonTypeT.GRASS): 2.0,
    (types.VibemonTypeT.FLYING, types.VibemonTypeT.FIGHTING): 2.0,
    (types.VibemonTypeT.FLYING, types.VibemonTypeT.BUG): 2.0,
    (types.VibemonTypeT.FLYING, types.VibemonTypeT.ROCK): 0.5,
    (types.VibemonTypeT.FLYING, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.PSYCHIC, types.VibemonTypeT.FIGHTING): 2.0,
    (types.VibemonTypeT.PSYCHIC, types.VibemonTypeT.POISON): 2.0,
    (types.VibemonTypeT.PSYCHIC, types.VibemonTypeT.PSYCHIC): 0.5,
    (types.VibemonTypeT.PSYCHIC, types.VibemonTypeT.DARK): 0.0,
    (types.VibemonTypeT.PSYCHIC, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.FIRE): 0.5,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.GRASS): 2.0,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.FIGHTING): 0.5,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.POISON): 0.5,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.FLYING): 0.5,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.PSYCHIC): 2.0,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.GHOST): 0.5,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.DARK): 2.0,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.BUG, types.VibemonTypeT.FAIRY): 0.5,
    (types.VibemonTypeT.ROCK, types.VibemonTypeT.FIRE): 2.0,
    (types.VibemonTypeT.ROCK, types.VibemonTypeT.ICE): 2.0,
    (types.VibemonTypeT.ROCK, types.VibemonTypeT.FIGHTING): 0.5,
    (types.VibemonTypeT.ROCK, types.VibemonTypeT.GROUND): 0.5,
    (types.VibemonTypeT.ROCK, types.VibemonTypeT.FLYING): 2.0,
    (types.VibemonTypeT.ROCK, types.VibemonTypeT.BUG): 2.0,
    (types.VibemonTypeT.ROCK, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.GHOST, types.VibemonTypeT.NORMAL): 0.0,
    (types.VibemonTypeT.GHOST, types.VibemonTypeT.PSYCHIC): 2.0,
    (types.VibemonTypeT.GHOST, types.VibemonTypeT.GHOST): 2.0,
    (types.VibemonTypeT.GHOST, types.VibemonTypeT.DARK): 0.5,
    (types.VibemonTypeT.DRAGON, types.VibemonTypeT.DRAGON): 2.0,
    (types.VibemonTypeT.DRAGON, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.DRAGON, types.VibemonTypeT.FAIRY): 0.0,
    (types.VibemonTypeT.DARK, types.VibemonTypeT.PSYCHIC): 2.0,
    (types.VibemonTypeT.DARK, types.VibemonTypeT.GHOST): 2.0,
    (types.VibemonTypeT.DARK, types.VibemonTypeT.DARK): 0.5,
    (types.VibemonTypeT.DARK, types.VibemonTypeT.FAIRY): 0.5,
    (types.VibemonTypeT.STEEL, types.VibemonTypeT.FIRE): 0.5,
    (types.VibemonTypeT.STEEL, types.VibemonTypeT.WATER): 0.5,
    (types.VibemonTypeT.STEEL, types.VibemonTypeT.ELECTRIC): 0.5,
    (types.VibemonTypeT.STEEL, types.VibemonTypeT.ICE): 2.0,
    (types.VibemonTypeT.STEEL, types.VibemonTypeT.ROCK): 2.0,
    (types.VibemonTypeT.STEEL, types.VibemonTypeT.STEEL): 0.5,
    (types.VibemonTypeT.STEEL, types.VibemonTypeT.FAIRY): 2.0,
    (types.VibemonTypeT.FAIRY, types.VibemonTypeT.FIRE): 0.5,
    (types.VibemonTypeT.FAIRY, types.VibemonTypeT.FIGHTING): 2.0,
    (types.VibemonTypeT.FAIRY, types.VibemonTypeT.POISON): 0.5,
    (types.VibemonTypeT.FAIRY, types.VibemonTypeT.DRAGON): 2.0,
    (types.VibemonTypeT.FAIRY, types.VibemonTypeT.DARK): 2.0,
    (types.VibemonTypeT.FAIRY, types.VibemonTypeT.STEEL): 0.5,
}


def get_type_effectiveness(attack_type: types.VibemonTypeT, defender_types: list[types.VibemonTypeT]) -> float:
    """
    Multiply the attacker's type modifier against each of the defender's types.

    Dual Type defenders produce combined multipliers
      4.00x = double weakness
      0.25x = double resistance
      1.00x = neutralization, when one type is weak and the other resists
      0.00x = absolute immunity, immunity on either type trumps any weakness on the other
    """
    modifier = 1.0

    for defender_type in defender_types:
        modifier *= TYPE_CHART.get((attack_type, defender_type), 1.0)

    return modifier
