FREEZE_THAW_CHANCE = 0.2
PARALYSIS_FULLY_PARALYZED_CHANCE = 0.25
CONFUSION_SELF_HIT_CHANCE = 0.33
BURN_DAMAGE_DIVISOR = 16
POISON_DAMAGE_DIVISOR = 8
CONFUSION_SELF_HIT_DIVISOR = 4

CRIT_THRESHOLDS = [1 / 24, 1 / 8, 1 / 2, 1.0]

STAT_STAGE_MIN = -6
STAT_STAGE_MAX = 6
STAT_ACCURACY_DIVISOR = 3
