"""Analyze saved Vibemon battle transcripts.

Default input is the 500-battle batch generated by run_500_battles.py.
"""

from __future__ import annotations

import argparse
import math
import re
import statistics
from collections import Counter, defaultdict
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BATTLE_DIR = ROOT / ".scripts" / "battle_runs" / "batch_500"
ELEMENT_CHART = ROOT / "backend" / "app" / "balance" / "element_chart.py"


def pct(part: int | float, whole: int | float) -> float:
    return 100 * part / whole if whole else 0.0


def mean(values: Iterable[int | float]) -> float:
    xs = list(values)
    return sum(xs) / len(xs) if xs else 0.0


def confidence_interval(wins: int, total: int) -> float:
    if total == 0:
        return 0.0
    p = wins / total
    return 1.96 * math.sqrt(p * (1 - p) / total) * 100


def tier_for_bst(bst: int) -> str:
    """Keep this in sync with backend.app.schema.Identity.tier."""
    if bst < 400:
        return "runt"
    if bst < 500:
        return "mid"
    if bst < 570:
        return "solid"
    if bst < 670:
        return "apex"
    return "mythic"


def load_element_chart(path: Path) -> dict[tuple[str, str], float]:
    text = path.read_text()
    return {
        (attack.lower(), defender.lower()): float(value)
        for attack, defender, value in re.findall(
            r"VibemonTypeT\.([A-Z_]+), types\.VibemonTypeT\.([A-Z_]+)\): ([0-9.]+)",
            text,
        )
    }


def effectiveness(attack_type: str, defender_types: tuple[str, ...], chart: dict[tuple[str, str], float]) -> float:
    out = 1.0
    for defender_type in defender_types:
        out *= chart.get((attack_type, defender_type), 1.0)
    return out


def parse_moves(text: str, side: str) -> dict[str, dict[str, str]]:
    match = re.search(rf"^{side}: .+?\n  Stats:.*?\n  Moves: (.+)$", text, re.MULTILINE)
    if not match:
        return {}

    moves = {}
    for name, move_type, category, power in re.findall(
        r"([^,\[]+?) \[([a-z]+), ([a-z]+), ([0-9-]+)\]",
        match.group(1),
    ):
        moves[name.strip()] = {"type": move_type, "category": category, "power": power}
    return moves


def parse_battle(path: Path) -> dict | None:
    text = path.read_text()
    headers = re.findall(
        r"^(Red|Blue): (.+?) Lv\.\d+ \((.+?)\) BST (\d+) HP",
        text,
        re.MULTILINE,
    )[:2]
    if len(headers) != 2:
        return None

    mons = {
        side: {
            "side": side,
            "name": name,
            "types": tuple(types_text.split("/")),
            "bst": int(bst),
            "tier": tier_for_bst(int(bst)),
            "moves": parse_moves(text, side),
        }
        for side, name, types_text, bst in headers
    }

    winner_match = re.search(r"^Winner: (Red|Blue)", text, re.MULTILINE)
    summary_match = re.search(r"Battle (\d+): .+ - (\d+) turns$", text.strip())
    if not winner_match or not summary_match:
        return None

    winner_side = winner_match.group(1)
    loser_side = "Blue" if winner_side == "Red" else "Red"
    return {
        "id": int(summary_match.group(1)),
        "turns": int(summary_match.group(2)),
        "winner_side": winner_side,
        "loser_side": loser_side,
        "mons": mons,
        "text": text,
    }


def analyze(battle_dir: Path) -> None:
    chart = load_element_chart(ELEMENT_CHART)
    files = sorted(battle_dir.glob("battle_*.txt"), key=lambda p: int(p.stem.split("_")[1]))

    side_wins = Counter()
    turns = []
    type_apps = Counter()
    type_wins = Counter()
    type_bst = defaultdict(list)
    combo_apps = Counter()
    combo_wins = Counter()
    tier_apps = Counter()
    tier_wins = Counter()
    single_dual_apps = Counter()
    single_dual_wins = Counter()
    species = defaultdict(lambda: {"apps": 0, "wins": 0, "bst": 0, "types": (), "turns": []})
    hit_effectiveness = Counter()
    hit_damage = Counter()
    coverage = Counter()
    coverage_turns = defaultdict(list)
    bst_diffs = []
    upsets = []
    longest = []

    for path in files:
        battle = parse_battle(path)
        if battle is None:
            continue

        mons = battle["mons"]
        winner_side = battle["winner_side"]
        loser_side = battle["loser_side"]
        winner = mons[winner_side]
        loser = mons[loser_side]
        battle_turns = battle["turns"]

        side_wins[winner_side] += 1
        turns.append(battle_turns)
        longest.append((battle_turns, battle["id"], winner, loser))

        for side, mon in mons.items():
            won = side == winner_side
            combo = "/".join(mon["types"])
            typing_kind = "single" if len(mon["types"]) == 1 else "dual"

            combo_apps[combo] += 1
            tier_apps[mon["tier"]] += 1
            single_dual_apps[typing_kind] += 1

            if won:
                combo_wins[combo] += 1
                tier_wins[mon["tier"]] += 1
                single_dual_wins[typing_kind] += 1

            species_row = species[mon["name"]]
            species_row["apps"] += 1
            species_row["wins"] += int(won)
            species_row["bst"] = mon["bst"]
            species_row["types"] = mon["types"]
            species_row["turns"].append(battle_turns)

            for mon_type in mon["types"]:
                type_apps[mon_type] += 1
                type_bst[mon_type].append(mon["bst"])
                if won:
                    type_wins[mon_type] += 1

        if winner["bst"] < loser["bst"]:
            upsets.append((loser["bst"] - winner["bst"], battle["id"], winner, loser, battle_turns))
        bst_diffs.append(winner["bst"] - loser["bst"])

        max_effectiveness = {}
        for side in ("Red", "Blue"):
            opponent = mons["Blue" if side == "Red" else "Red"]
            values = [
                effectiveness(move["type"], opponent["types"], chart)
                for move in mons[side]["moves"].values()
                if move["category"] != "status"
            ]
            max_effectiveness[side] = max(values) if values else 0.0

        if max_effectiveness["Red"] == max_effectiveness["Blue"] == 1.0:
            coverage_label = "both best neutral"
        elif max_effectiveness["Red"] == max_effectiveness["Blue"] and max_effectiveness["Red"] > 1.0:
            coverage_label = "both have super-effective"
        elif max_effectiveness["Red"] == max_effectiveness["Blue"] and max_effectiveness["Red"] < 1.0:
            coverage_label = "both resisted/no neutral"
        elif max_effectiveness[winner_side] > max_effectiveness[loser_side]:
            coverage_label = "winner had better coverage"
        else:
            coverage_label = "winner overcame coverage disadvantage"
        coverage[coverage_label] += 1
        coverage_turns[coverage_label].append(battle_turns)

        name_to_side = {mon["name"]: side for side, mon in mons.items()}
        for user, move_name, target, damage, meta in re.findall(
            r"^- (.+?): (.+?) hit (.+?) for (\d+) \(([^)]*)\)",
            battle["text"],
            re.MULTILINE,
        ):
            user_side = name_to_side.get(user)
            target_side = name_to_side.get(target)
            if not user_side or not target_side:
                continue
            multiplier_match = re.search(r"(0\.25|0\.5|1|2|4)x", meta)
            multiplier = float(multiplier_match.group(1)) if multiplier_match else 1.0
            bucket = "super" if multiplier > 1 else "resisted" if multiplier < 1 else "neutral"
            hit_effectiveness[bucket] += 1
            hit_damage[bucket] += int(damage)

    total = len(turns)
    print(f"Parsed battles: {total} / {len(files)}")
    print(f"Red wins: {side_wins['Red']} ({pct(side_wins['Red'], total):.1f}%)")
    print(f"Blue wins: {side_wins['Blue']} ({pct(side_wins['Blue'], total):.1f}%)")
    print(
        "Turns: "
        f"avg {mean(turns):.1f}, median {statistics.median(turns):.0f}, "
        f"min {min(turns)}, max {max(turns)}"
    )

    print("\nTier distribution / win rate")
    for tier in ("runt", "mid", "solid", "apex", "mythic"):
        apps = tier_apps[tier]
        if apps:
            print(
                f"{tier:6} apps {apps:3} ({pct(apps, total * 2):4.1f}%) "
                f"wins {tier_wins[tier]:3}/{apps:<3} "
                f"({pct(tier_wins[tier], apps):5.1f}% +/-{confidence_interval(tier_wins[tier], apps):.1f})"
            )

    print("\nSingle vs dual")
    for kind in ("single", "dual"):
        apps = single_dual_apps[kind]
        print(
            f"{kind:6} apps {apps:3} ({pct(apps, total * 2):4.1f}%) "
            f"wins {single_dual_wins[kind]:3}/{apps:<3} ({pct(single_dual_wins[kind], apps):5.1f}%)"
        )

    print("\nType distribution and win rate")
    element_total = sum(type_apps.values())
    for mon_type, apps in sorted(type_apps.items(), key=lambda item: (-item[1], item[0])):
        print(
            f"{mon_type:8} apps {apps:3} "
            f"({pct(apps, element_total):4.1f}% elem, {pct(apps, total * 2):4.1f}% mons) "
            f"wins {type_wins[mon_type]:3}/{apps:<3} "
            f"({pct(type_wins[mon_type], apps):5.1f}%) avg BST {mean(type_bst[mon_type]):.0f}"
        )

    print("\nTop type combos, min 8 appearances")
    combos = [
        (apps, pct(combo_wins[combo], apps), combo, combo_wins[combo])
        for combo, apps in combo_apps.items()
        if apps >= 8
    ]
    for apps, win_rate, combo, wins in sorted(combos, key=lambda item: (-item[0], -item[1]))[:12]:
        print(f"{combo:17} apps {apps:3} wins {wins:3}/{apps:<3} ({win_rate:5.1f}%)")

    print("\nDamaging hit effectiveness")
    total_hits = sum(hit_effectiveness.values())
    for bucket in ("neutral", "super", "resisted"):
        hits = hit_effectiveness[bucket]
        print(
            f"{bucket:8} hits {hits:4}/{total_hits:<4} ({pct(hits, total_hits):5.1f}%), "
            f"avg dmg {hit_damage[bucket] / hits if hits else 0:.2f}"
        )

    print("\nPre-battle coverage categories")
    for label, count in coverage.most_common():
        print(f"{label:39} {count:3} ({pct(count, total):5.1f}%) avg turns {mean(coverage_turns[label]):.1f}")

    higher_won = sum(1 for diff in bst_diffs if diff > 0)
    print("\nBST advantage")
    print(f"Higher BST won: {higher_won}/{total} ({pct(higher_won, total):.1f}%)")
    for threshold in (10, 25, 50, 75, 100):
        subset = [diff for diff in bst_diffs if abs(diff) >= threshold]
        won = sum(1 for diff in subset if diff > 0)
        if subset:
            print(f"BST gap >= {threshold:3}: higher won {won}/{len(subset)} ({pct(won, len(subset)):.1f}%)")

    print("\nSpecies outliers, min 8 appearances")
    qualified_species = [
        (
            pct(row["wins"], row["apps"]),
            row["apps"],
            row["wins"],
            name,
            row["bst"],
            "/".join(row["types"]),
            mean(row["turns"]),
        )
        for name, row in species.items()
        if row["apps"] >= 8
    ]
    for win_rate, apps, wins, name, bst, types_text, avg_turns in sorted(qualified_species, reverse=True)[:8]:
        print(f"TOP {name:14} {types_text:14} BST {bst:3} {wins:2}/{apps:<2} {win_rate:5.1f}% avgT {avg_turns:.1f}")
    for win_rate, apps, wins, name, bst, types_text, avg_turns in sorted(qualified_species)[:8]:
        print(f"BOT {name:14} {types_text:14} BST {bst:3} {wins:2}/{apps:<2} {win_rate:5.1f}% avgT {avg_turns:.1f}")

    print("\nLongest battles")
    for battle_turns, battle_id, winner, loser in sorted(longest, reverse=True)[:8]:
        print(
            f"{battle_id:03} {battle_turns:2} turns: "
            f"{winner['name']} {'/'.join(winner['types'])} beat {loser['name']} {'/'.join(loser['types'])}"
        )

    print("\nLargest upsets")
    for gap, battle_id, winner, loser, battle_turns in sorted(upsets, reverse=True)[:8]:
        print(
            f"{battle_id:03} gap {gap:3}: {winner['name']} {winner['bst']} "
            f"{'/'.join(winner['types'])} beat {loser['name']} {loser['bst']} "
            f"{'/'.join(loser['types'])} in {battle_turns} turns"
        )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "battle_dir",
        nargs="?",
        type=Path,
        default=DEFAULT_BATTLE_DIR,
        help="Directory containing battle_*.txt transcripts.",
    )
    args = parser.parse_args()
    analyze(args.battle_dir.resolve())


if __name__ == "__main__":
    main()
